spring:
  application:
    name: slack-mcp-server
  main:
    banner-mode: off
    web-application-type: none
  ai:
    mcp:
      server:
        name: slack-mcp-server
        version: 1.0.0
        stdio: true
        type: sync
        instructions: "Slack MCP Server is a server that allows you to interact with Slack's API using the Model Context Protocol."

server:
  port: 8180

logging:
  pattern:
    console:

slack:
  slack-bot-token: ${SLACK_BOT_TOKEN}
  slack-channel-id: ${SLACK_CHANNEL_ID}
