spring:
  main:
    banner-mode: off
  ai:
    mcp:
      server:
        name: mcp-server-example
        version: 0.0.1
        type: SYNC
        sse-endpoint: /sse
        sse-message-endpoint: /mcp/messages